language: node_js
node_js:
- node
cache: npm
script:
- make lint
- make test
deploy:
  provider: heroku
  app: ch-taskman
  api_key:
    secure: bm7PBsRvpZgH8AaCazWNfA9hWKHVbEZJQFM0Z6ZusfzkmOVP6t5KxphjYQgzF1HR7KMv2eUtTrxUD9Gz16T9zwAjNO3grN4ILd3FxblMdRbRYoLNx2/URmUjZo7JGDbRHX0VpGOeAVsI17kksoVSJq6y6X6Thb22prhwFk2A8WKW+uNNPTbYtEwgC/5iwLt781cHdFUVaDO68RsRFwTHKRHt56SzkpOycAUByjYYXoJn3ZK0g4nZLNltamdBehv6kijrPqgCA2cYu73czd8N4nUnzSaE5LSBYXFatvzl1OJ7L+fEPS1tRzuLRjfoIdTxC0MxDVeht5IPd+rcKo/D/lJS0y7pF49pGSztPkrJDmtNX0xcrdQX5aNLut7OKoLoAgQNwisa6VOq/suoFkLDf1YG1dObGxSCRCaQrgEFFWnTDmw/D5pzt/c//reGqjcJGHwHrkzTGlSVX+G8xyh8iQfu0HZQDepqY65kBTd8pT35PY7TuYgw4hUSv7EVwJ41nBO14ONqSiECUo8qRH9DNXMxpl9ghollSWB5f7p0z72MAPU3a2qF6GO6FfnqWo0HcOnSRyANzThCmb40Fb1yYuQ5UIjXJg95cWT7OYz4mWukEfZgSPKfKWgYEnoTr1aUB/O6vQQXE/41nDQlwWvhRPblnp/4NG1tB5iJFMObJTI=
  skip_cleanup: true
