language: node_js
node_js:
- node
env:
  - APPKEY=GNS5x1q27jf0HS32U3yaeUyjcNa8YA1j CRYPTOWORD=TRAVIS
cache: npm
script:
- make lint
- make test
deploy:
  provider: heroku
  app: ch-taskman
  api_key:
    secure: TMugLzCbOfnVA6ZDlUHCOTTVCd2RythSUjf7zxZ0XLKpq/gZ6iZzFoFu3a1Gjf9TOJ5aJ79nkA3+ELJjNQPQ9JUV8VCX+9Z0gyrHodpzZG2eIRHZIBUNDAMxpJYuIaz38hGGB9k1H3HLDHvHZQzqIsyHcOLAiQA5GGaO91vniHkkbbRAGiTDWJw9wlU1wMDF4ZT5K9mkAfYE6ZJZpYV3SNb1/j4yHx7FBs+bCNobKnJaMpQP+kUEGd0gy3BolINj6ptZFkHFjg+atqMoaEyqjer69/nBT7B9v7HOV6OqxFCB3JcF5ST2pD8Ji0cYn0ZfnMYDd4zEl8dDDSngTwmbVLJ/dOc8MCFXwJRljuwrwjndkTgw9V9fJ+ZyFcaP4Rkx+gXolYFggvxlDzEeMzQqFblQbHE5YSamBcV4MCIQK1/+GkujhivCxhf8CMefEREra2QyHDt7hT7P8/ZjJTi4kbRaXdYmj4mXSNf6oWAi5DdL1uDrb0t7mrxqsO5ZGypnTuJDfpbfOfJYCfEL27lDRCDXRae6zWLQp9HGQT1vMxYxfikfeJPwTyjtg85ox/k8/EJQyS2fAgk1SFI2BtQnE+JwPbLIYJd1DM8ASt2xUICB5e7r4leIR9MpKDMY6TJMxs2LlM1IguRTZ1d7OACxLScD5qwEnedrfBNdCqtuS9M=
