# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CI:
    runs-on: ubuntu-latest
    
    env:
      APPKEY: ${{secrets.APPKEY}}
      CRYPTOWORD: ${{secrets.CRYPTOWORD}}

    steps:
      - uses: actions/checkout@v2

      - name: install
        run: make install

      - name: Lint
        run: make lint
      
      - name: Test
        run: make test

      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
